development:
  adapter: postgresql
  encoding: unicode
  database: tushman_development
  pool: 5

test:
    adapter: postgresql
    encoding: unicode
    database: tushman_test
    pool: 5

production:
    adapter: postgresql
    encoding: unicode
    database: tushman_production
    pool: 5