--- # Work Experience
- school: Harvard Business School
  degree: 'MBA'
  class: 2004
  logo: hbs_logo3.jpg
  url: 'http://hbs.edu'

- school: University of Rochester
  degree: 'BSEE'
  class: 1997
  logo: u_of_r.jpg
  url: 'http://www.rochester.edu'

