--- # Favorite Games
- name: Agricola
  url: http://boardgamegeek.com/boardgame/31260/agricola
  image: http://cf.geekdo-images.com/images/pic259085_t.jpg
  description: |
    This has been our favorite for 3 years running.  My wife even loves to play.  Great replay-ablity and theme
- name: Through the Ages
  url: http://boardgamegeek.com/boardgame/25613/through-the-ages-a-story-of-civilization
  image: http://cf.geekdo-images.com/images/pic236169_t.jpg
  description: |
      My most recent purchase, and it is getting a lot of table time.  Its a board game version of the classic
      computer game Civilization.  But it is brilliantly designed