--- # Favorite Games
- name: Agricola
  url: http://boardgamegeek.com/boardgame/31260/agricola
  image: http://cf.geekdo-images.com/images/pic259085_t.jpg
- name: Through the Ages
  url: http://boardgamegeek.com/boardgame/25613/through-the-ages-a-story-of-civilization
  image: http://cf.geekdo-images.com/images/pic236169_t.jpg