--- # Favorite Albums
- artist: Joni Mitchel
  album: Blue
  image: http://static.rhap.com/img/170x170/8/2/0/2/3012028_170x170.jpg
- artist: Who
  album: Tommy
  image: http://static.rhap.com/img/170x170/9/7/0/2/1302079_170x170.jpg
- artist: Big Star
  album: '#1 Record / Radio City'
  image: http://static.rhap.com/img/170x170/8/9/5/8/2998598_170x170.jpg