--- # Favorite Technologies
- technology: Ruby on Rails
  url: 'http://rubyonrails.org/'
  image: rails.png
  description: |
    Been developing with Ruby and Rails for over 4 years.  I have never had more fun or have been more productive than
    I have been working with Ruby.  The DRY (don't repeat yourself) philosophy or Rails, combined with the elegance of
    Ruby make it such a killer combination.  Also, the supporting community (Thanks [Ryan](http://railscasts.com)!) really push to you to keep
    learning new libraries and hone your skills

- technology: MongoDB
  url: 'http://www.mongodb.org/'
  image: mongo.png
  description: |
    I have been really impressed with Mongo.  I love not having to deal with migrations anymore.  The DSL of
    [Mongoid](http://mongoid.org)The performance and scalability (at least for the types of applications that I have
    built) have been really impressive.  Plus, I have to give a shoutout to the folks at [MongoHQ](http://mongohq.com)
    who have phenominal support and have been great system admins for my projects

- technology: jQuery
  url: 'http://jquery.com/'
  image: 'http://static.jquery.com/files/rocker/images/logo_jquery_215x53.gif'
  description: |
    As the browsers become more powerful, developers need to rely on javascript to give the users fast, responsive,
    and an impactful experience.  For now, jQuery is my library of choice

- technology: heroku
  url: 'http://heroku.com/'
  image: heroku-logo.png
  description: |
    While not all my projects run on heroku, most do.  It really allows me to focus on the business-domain of the
    problem that I am solving, and leave the infrastructure to them.
